{{- if .Values.slackEventsCatcher.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "les-projets-cagnottes.fullname" . }}-slack-events-catcher
  labels:
    {{- include "les-projets-cagnottes.labels" . | nindent 4 }}
    component: slack-events-catcher
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "les-projets-cagnottes.fullname" . }}-slack-events-catcher
  minReplicas: {{ .Values.slackEventsCatcher.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.slackEventsCatcher.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.slackEventsCatcher.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.slackEventsCatcher.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.slackEventsCatcher.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.slackEventsCatcher.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
