{{- if .Values.slack.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "les-projets-cagnottes.fullname" . }}-slack-events-catcher
  labels:
    {{- include "les-projets-cagnottes.labels" . | nindent 4 }}
    component: slack-events-catcher
spec:
  type: {{ .Values.slackEventsCatcher.service.type }}
  ports:
    - port: {{ .Values.slackEventsCatcher.controller.servicePort }}
      targetPort: {{ .Values.slackEventsCatcher.controller.containerPort }}
      protocol: TCP
      name: controller
    - port: {{ .Values.slackEventsCatcher.bot.servicePort }}
      targetPort: {{ .Values.slackEventsCatcher.bot.containerPort }}
      protocol: TCP
      name: bot
  selector:
    {{- include "les-projets-cagnottes.selectorLabels" . | nindent 4 }}
    component: slack-events-catcher
{{- end }}
