apiVersion: v2
name: les-projets-cagnottes
description: Helm chart to deploy Les Projets Cagnottes in a Kubernetes cluster
type: application
version: 0.10.1
appVersion: "0.14.1"
dependencies:
- name: postgresql
  version: "11.9.13"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled
