# Default values for les-projets-cagnottes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

api:

  replicaCount: 1

  image:
    repository: lesprojetscagnottes/api
    pullPolicy: IfNotPresent
    tag: "0.17.0"

  containerPort: 8080

  service:
    type: ClusterIP
    port: 80

  podAnnotations: {}

  podSecurityContext: 
    runAsUser: 1000
    fsGroup: 1000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  env: {}
    # SPRING_JPA_HIBERNATE_DDL-AUTO: update
    # LOGGING_LEVEL_FR_LESPROJETSCAGNOTTES: INFO
    # FR_LESPROJETSCAGNOTTES_ADMINPASSWORD: admin
    # FR_LESPROJETSCAGNOTTES_CORE_URL: https://les-projets-cagnottes.fr

  secretsEnv: []
    # - secretName: ""
    #   env:
    #     FOO: barKey

  resources: {}
    # limits:
    #   memory: 512Mi
    # requests:
    #   cpu: 5m
    #   memory: 512Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

web:
  replicaCount: 1

  image:
    repository: lesprojetscagnottes/web
    pullPolicy: IfNotPresent
    tag: "0.16.0"

  containerPort: 80

  url: "http://les-projets-cagnottes.localhost"
  config: |-
    {
      "webUrl": "http://localhost:4200",
      "apiUrl": "http://localhost:8080/api",
      "slackEnabled": false,
      "slackClientId": "1267900044419.1280463132273",
      "microsoftEnabled": false,
      "microsoftTenantId": "ab8f3573-a42c-4b8b-a615-f03fd683bbbd",
      "microsoftClientId": "08a651e0-9f49-4984-9834-2ad26a490f86"
    }

  service:
    type: ClusterIP
    port: 80

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  resources: {}
    # limits:
    #   memory: 64Mi
    # requests:
    #   cpu: 1m
    #   memory: 64Mi
    
  nodeSelector: {}

  tolerations: []

  affinity: {}

slackEventsCatcher:

  replicaCount: 1

  image:
    repository: lesprojetscagnottes/slack-events-catcher
    pullPolicy: IfNotPresent
    tag: "0.7.0"

  service:
    type: ClusterIP
    port: 80

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  env: {}
    # SPRING_JPA_HIBERNATE_DDL-AUTO: update
    # LOGGING_LEVEL_FR_LESPROJETSCAGNOTTES: INFO

  secretsEnv: []
    # - secretName: ""
    #   env:
    #     FOO: barKey

  resources: {}
    # limits:
    #   memory: 32Mi
    # requests:
    #   cpu: 1m
    #   memory: 32Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: les-projets-cagnottes.localhost
      paths:
      - path: /
        backend:
          serviceName: les-projets-cagnottes-web
          servicePort: 80
      - path: /api/
        backend:
          serviceName: les-projets-cagnottes-api
          servicePort: 80
      - path: /slack/events/
        backend:
          serviceName: les-projets-cagnottes-slack-events-catcher
          servicePort: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# Must be enabled in order to make slack-events-catcher to work
persistence: {}
  # enabled: true
  # accessMode: ReadWriteOnce
  # size: 1Mi

db:
  host: lesprojetscagnottes-postgresql
  port: 5432
  name: lesprojetscagnottes
  # existingSecret:
  #   name: db-lesprojetscagnottes
  #   usernameKey: username
  #   passwordKey: password

postgresql:
  enabled: true
  fullnameOverride: lesprojetscagnottes-postgresql
  auth:
    username: lesprojetscagnottes
    password: lesprojetscagnottes
    database: lesprojetscagnottes
  volumePermissions:
    enabled: true

slack: {}
  # enabled: true
  # existingSecret:
  #   name: les-projets-cagnottes-slack
  #   clientIdKey: clientId
  #   clientSecretKey: clientSecret
  #   signingSecretKey: signingSecret

microsoft: {}
  # enabled: true
  # existingSecret:
  #   name: les-projets-cagnottes-microsoft
