apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "les-projets-cagnottes.fullname" . }}-api
  labels:
    {{- include "les-projets-cagnottes.labels" . | nindent 4 }}
    component: api
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "les-projets-cagnottes.selectorLabels" . | nindent 6 }}
      component: api
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "les-projets-cagnottes.selectorLabels" . | nindent 8 }}
        component: api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "les-projets-cagnottes.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: api
              containerPort: {{ .Values.api.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: api
          readinessProbe:
            httpGet:
              path: /api/health
              port: api
          env:
            - name: PORT
              value: "{{ .Values.api.port }}"
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.db.url }}
            - name: LPC_WEB_URL
              value: {{ .Values.web.url }}
            - name: FR_LESPROJETSCAGNOTTES_SLACK_ENABLED
              value: "{{ .Values.slack.enabled | default false }}"
            {{- if .Values.db.existingSecret }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret.name }}
                  key: {{ .Values.db.existingSecret.usernameKey }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret.name }}
                  key: {{ .Values.db.existingSecret.passwordKey }}
            {{- else if .Values.postgresql.enabled }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
            {{- end }}
            {{- if .Values.slack.existingSecret }}
            - name: LPC_SLACK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.slack.existingSecret.name }}
                  key: {{ .Values.slack.existingSecret.clientIdKey }}
            - name: LPC_SLACK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.slack.existingSecret.name }}
                  key: {{ .Values.slack.existingSecret.clientSecretKey }}
            {{- end }}
            {{- range .Values.api.secretsEnv }}
              {{- $secretName := .secretName }}
              {{- range $key, $value :=  .env }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $value }}
              {{- end }}
            {{- end }}
            {{- range $key, $value := .Values.api.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name : config
              mountPath : /files/config
          {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "les-projets-cagnottes.fullname" .) }}
      {{- end -}}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
