{{- if .Values.slack.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "les-projets-cagnottes.fullname" . }}-slackeventscatcher
  labels:
    {{- include "les-projets-cagnottes.labels" . | nindent 4 }}
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
    {{- else }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
    {{- end }}
  {{- end }}
{{- end }}
