apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "les-projets-cagnottes.fullname" . }}-web
  labels:
    {{- include "les-projets-cagnottes.labels" . | nindent 4 }}
    component: web
data:
  config.json: '{{ .Values.web.config }}'
